### ISSUE TITLE
Lazy.force loop (Undefined) during resolution of sexplib.112.06.00/lib/type_with_layout.mli

### ISSUE THREAD

**Issue by dsheets** [lpw25/doc-ock-lib#36]
This has something to do with resolving type names in signature arguments from signatures in functor bodies.

**Comment by dsheets** [comment]
This is the most critical of the currently outstanding issues.

**Comment by Drup** [comment]
Also in ocsigenserver: 

```
/home/gabriel/.opam/4.02.1+doc/build/ocsigenserver.2.5/src/server/ocsigen_extensions.cmti
codoc: internal error, uncaught exception:
       CamlinternalLazy.Undefined
'codoc doc --scheme file --package ocsigenserver.2.5 /home/gabriel/.opam/4.02.1+doc/build/ocsigenserver.2.5 -o foobar' exited with code 1
```

**Comment by lpw25** [comment]
This was caused by include statements including a module defined in the same signature. I have commited a fix that short-curcuits lookups of local modules, so that local modules can be looked up before their surrounding signature has been fully defined.
