### ISSUE TITLE
DocOckEnvironment.read_class_type_ident asserts on lwt.2.4.5 syntax/pa_lwt_log.cmti

### ISSUE THREAD

**Issue by dsheets** [lpw25/doc-ock-lib#41]
```
lwt.2.4.5/_build/syntax/pa_lwt_log.cmti
codoc: internal error, uncaught exception:
       File "_build/lib-doc-ock/docOckEnvironment.cml-native", line 306, characters 22-28: Assertion failed
       
'codoc doc --package lwt.2.4.5 /home/dsheets/.opam/doc/build/lwt.2.4.5 -o test-opam-glue' exited with code 1
```

**Comment by dsheets** [comment]
This is higher severity than #36 and presently the most urgent issue.

**Comment by dsheets** [comment]
Same error for camomile.0.8.5 `camomileLibraryDefault.cmti`.

**Comment by lpw25** [comment]
I can't reproduce this with my test progam:

```
./testCmti ~/.opam/4.02.1+doc/build/lwt.2.4.5/_build/syntax/pa_lwt_log.cmti
```

I'll with `codoc` itself.

**Comment by dsheets** [comment]
Maybe the `lookup` -> `None` case in the test program? I have a lot of stuff loaded in the resolution environment.

**Comment by Drup** [comment]
Same error for ocamlnet.3.7.7 : 
```
/home/gabriel/.opam/4.02.1+doc/build/ocamlnet.3.7.7/src/netcgi2-plex/netcgi_plex.cmti
codoc: internal error, uncaught exception:
       File "_build/lib-doc-ock/docOckEnvironment.cml-native", line 306, characters 22-28: Assertion failed
```

**Comment by lpw25** [comment]
The `lookup -> None` is to do with resolution, but `docOckEnvironment` is about looking up local identifiers which is done as part of reading the cmti file.

**Comment by lpw25** [comment]
I don't know how to use codoc. I just get:

```
codoc: internal error, uncaught exception:
       Sys_error("share/codoc.css: No such file or directory")
```

**Comment by lpw25** [comment]
Okay, now I am failing to reproduce with codoc:

```
$codoc doc -o lwt ~/.opam/4.02.1+doc/build/lwt.2.4.5/_build/syntax/pa_lwt_log.cmti
/home/leo/.opam/4.02.1+doc/build/lwt.2.4.5/_build/syntax/pa_lwt_log.cmti
```

**Comment by lpw25** [comment]
Okay I've reproduced it now

**Comment by lpw25** [comment]
The problem is not in `pa_lwt_log.cmti` it is in whichever file codoc is looking at *after* `pa_lwt_log.cmti` -- the printing of the file name seems to be done after the error. This is why I couldn't reproduce the bug with the test program.

**Comment by dsheets** [comment]
printf here <https://github.com/dsheets/codoc/blob/master/cli/codocCliDoc.ml#L301>

**Comment by lpw25** [comment]
I had it backwards. `pa_lwt_log.cmti` is the last file looked at. The error then happens when `lwt_engine.cmti` is processed -- which happens later than the printfs. I can now reproduce the error using the test program.

**Comment by lpw25** [comment]
Fixed. Although `lwt` now fails due to #36.
