### ISSUE TITLE
Tag a release

### ISSUE THREAD

**Issue by dsheets** [lpw25/doc-ock-lib#47]
I think the current head is what I'd like to reference for codoc 0.2.0. A tag would be helpful.

**Comment by lpw25** [comment]
Tag 0.2.0 added to this and doc-ock-xml.

**Comment by dsheets** [comment]
Could you make a branch with the results of `assemblage setup`, update the opam file to remove the assemblage dep, and force-push the tag to that branch? I'd like to release to platform-dev without the assemblage requirement as there is now a new, incompatible version.

**Comment by lpw25** [comment]
Done
